version: "3.4"
services:
  audit-log-browser-share:
    image: alfresco-share-audit-log-browser:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../audit-log-browser-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: audit-log-browser-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  audit-log-browser-acs:
    image: alfresco-content-services-audit-log-browser:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../audit-log-browser-platform-docker/target
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      JAVA_OPTS: '
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dfile.encoding=UTF-8
        -Dmessaging.broker.url="failover:(nio://audit-log-browser-activemq:61616)?timeout=3000&jms.useCompression=true"
        '
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - audit-log-browser-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - audit-log-browser-postgres
  audit-log-browser-postgres:
    image: postgres:14.8
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - audit-log-browser-db-volume:/var/lib/postgresql/data
  audit-log-browser-ass:
    image: alfresco/alfresco-search-services:2.0.3
    environment:
      SOLR_ALFRESCO_HOST: audit-log-browser-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: audit-log-browser-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: "secret"
      JAVA_TOOL_OPTIONS: "-Dalfresco.secureComms.secret=secret"
    ports:
      - "8983:8983"
    volumes:
      - audit-log-browser-ass-volume:/opt/alfresco-search-services/contentstore
      - audit-log-browser-ass-volume:/opt/alfresco-search-services/data
  audit-log-browser-activemq:
    image: alfresco/alfresco-activemq:5.16.1
    mem_limit: 1g
    ports:
      - 8161:8161 # Web Console
      - 5672:5672 # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP
volumes:
  audit-log-browser-acs-volume:
    external: true
  audit-log-browser-db-volume:
    external: true
  audit-log-browser-ass-volume:
    external: true
